# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'bento/ubuntu-23.04'

  config.vm.hostname = 'ttps'

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  config.vm.network 'forwarded_port', guest: 3000, host: 3000, host_ip: '127.0.0.1'

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network 'private_network', ip: '10.10.10.10'

  config.vm.synced_folder '.', '/home/vagrant/host'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'TTPS Ruby'
    vb.gui = false
    vb.memory = '1024'
  end

  config.vm.provision 'shell', inline: <<-SH
    sudo apt update -qq
    sudo apt upgrade -y
  SH
end
